services:
  mysqldb:
    image: mariadb:10.4.32
    container_name: mysqlcontainer
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      

    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: database_development
      
      MYSQL_PASSWORD: letmein
      MYSQL_ROOT_PASSWORD: letmein
      SERVICE_TAGS: prod
      SERVICE_NAME: mysqldb
    networks:
      - internalnet



  nodeapp:
    container_name: nodeappcontainer
    build: .
    image: nodeapp:v1
    restart: unless-stopped
    volumes:
      - $HOME/nodeapp:/code
    ports:
      - 3000:3000
    expose:
      - 3000
    environment:
      DB_HOST: mysqldb
      DB_PORT: 3306
      DB_USER: 'admin'
      DB_PASSWORD: 'letmein'
      DB_NAME: database_development
      DB_CONNECTION_LIMIT: 20
      NODE_ENV: test
      SERVICE_NAME: nodeappservice
      SERVER_PORT: 3000
    depends_on:
      - mysqldb
    networks:
      - internalnet
        
networks:
  internalnet:
    driver: bridge